# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaxf', '0007_auto_20181105_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodsTypes',
            new_name='FoodTypes',
        ),
    ]
